artifact_location: file:///C:/Users/anna_/PycharmProjects/pythonProject3/kobe/mlflow_runs/0
creation_time: 1743958324369
experiment_id: '0'
last_update_time: 1743958324369
lifecycle_stage: active
name: Default
