aliases: []
creation_timestamp: 1743962990761
current_stage: None
description: ''
last_updated_timestamp: 1743962990761
name: kobe_dt_model
run_id: cdbb3af8487c497481b6d46e26972cf8
run_link: ''
source: models:/kobe_dt_model/3
status: READY
status_message: null
storage_location: file:///C:/Users/anna_/PycharmProjects/pythonProject3/kobe/mlflow_runs/449109977047084958/cdbb3af8487c497481b6d46e26972cf8/artifacts/model
user_id: null
version: 4
