aliases: []
creation_timestamp: 1743958367058
current_stage: None
description: null
last_updated_timestamp: 1743958367058
name: kobe_lr_model
run_id: 5515ea526ed64e128344b3984519bf3e
run_link: null
source: file:///C:/Users/anna_/PycharmProjects/pythonProject3/kobe/mlflow_runs/449109977047084958/5515ea526ed64e128344b3984519bf3e/artifacts/model
status: READY
status_message: null
storage_location: file:///C:/Users/anna_/PycharmProjects/pythonProject3/kobe/mlflow_runs/449109977047084958/5515ea526ed64e128344b3984519bf3e/artifacts/model
user_id: null
version: 1
